---
# Default VM configuration values

# Default OS and Image Configuration
default_vm_os_type: "linux"
default_vm_image_source: "quay.io/containerdisks/fedora:latest"

# Network Configuration Defaults
default_vm_network_type: "pod"
default_vm_expose_service: false
default_vm_service_type: "ClusterIP"

# Default service ports for common applications
default_service_ports:
  ssh:
    - name: "ssh"
      port: 22
      target_port: 22
      protocol: "TCP"

# Storage Defaults
default_storage_class: "nfs-client"  # NFS storage operator storage class
default_additional_disks: []
default_ssh_public_key: ""

# VM wait timeouts (in seconds)
vm_creation_timeout: 600
vm_ready_timeout: 300
vm_deletion_timeout: 300
datavolume_timeout: 600

# Labels applied to all VM resources
default_vm_labels: "{{ {vm_order_label: vm_order_name} }}"
